# Generated by Django 5.2.9 on 2025-12-05 07:20

import tracker.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_submission_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='nrp',
            field=models.CharField(default=tracker.models.Student.generate_nrp, max_length=20, unique=True),
        ),
    ]
