# Generated by Django 5.2.9 on 2025-12-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_student_nrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='lecturer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='lecturer_name',
            field=models.CharField(max_length=200),
        ),
    ]
